yoshuawuyts/fd-lock

- src/windows.rs
Fixes the Windows code, resolving #2. The only downside of this patch is that I had to disable the `lock` function because I'm unsure how to initialize the OVERLAPPED struct (something I still need to learn, heh).
Either way, this should be better now. Thanks!
> Fix windows

- Cargo.toml
Depend on `winapi` crate only on `windows` target.
`winapi` is only required on `windows` target, but it is currently fetched even for "unix" platforms. With this PR merged, the amount of downloaded data is reduced significantly on non-windows targets.
> Reduce dependencies on non-windows targets

- src/unix.rs
- tests/test.rs
Closes #8 by checking errno (via `std::io::Error::last_os_error()`) instead of checking the return value of `flock` directly.
> Determine cause of failure from errno

- Cargo.toml
- src/lib.rs
- src/sys/windows/read_guard.rs
- src/sys/windows/rw_lock.rs
- src/sys/windows/utils.rs
- src/sys/windows/write_guard.rs
This moves us from `winapi` to `windows-sys` crate for our dependencies. Thanks!
> Migrate to `windows-sys`

- README.md
fd-lock has already switched from winapi to windows-sys; this just
updates the README to mention windows-sys as well.
> Update README.md to describe windows-sys instead of winapi.

- Cargo.toml
- README.md
- src/sys/unix/mod.rs
- src/sys/unix/read_guard.rs
- src/sys/unix/rw_lock.rs
- src/sys/unix/utils.rs
- src/sys/unix/write_guard.rs
- src/sys/unsupported/read_guard.rs
- src/sys/unsupported/rw_lock.rs
- src/sys/unsupported/write_guard.rs
Use rustix instead of calling libc directly, which factors out several
unsafe blocks and simplifies error handling.
There is still one `unsafe` block needed, to dereference raw file
descriptors passed in from the user, since the crate still uses
`AsRawFd`. Once I/O safety is stablized in std, this crate can switch
to using `AsFd`, which will eliminate the last `unsafe` block.
This splits out just the API-compatible parts of #14. It does not include
the changes to use the `AsFd` trait in the public API, so it's not an
API-breaking change.
> Use rustix instead of calling libc directly.

- Cargo.toml
- src/sys/unix/rw_lock.rs
`BorrowFd::borrow_raw_fd` was renamed to `BorrowFd::borrow_raw` to match the
[API in nightly].
[API in nightly]: https://doc.rust-lang.org/nightly/std/os/unix/io/struct.BorrowedFd.html#method.borrow_raw
> Update rustix to version 0.34.0

- Cargo.toml
The main change for fd-lock is that most of rustix is now behind feature
flags, so that crates like fd-lock can only enable the features they
need, like "fs". This makes `cargo build` of fd-lock from a clean tree
about 20% faster on my machine.
> Update to rustix 0.35.

- Cargo.toml
This adds supports for new Tier 3 Windows targets.
> Update `windows-sys` to version 0.42

- Cargo.toml
This is a minor update; the main change is that it uses io-lifetimes 1.0 internally, which means that on Rust 1.64 and later it's using the `OwnedFd` etc. from std instead of its own. This is not exposed in fd-lock's public API.
> Update to rustix 0.36.

- src/sys/windows/rw_lock.rs
- tests/test.rs
Fixes #35. I also added a test to confirm the correct behavior, based on the example shown in the issue.
> Return correct Error for try_* functions on Windows

- src/read_guard.rs
- src/sys/windows/read_guard.rs
- src/sys/windows/write_guard.rs
- src/write_guard.rs
Fixes https://github.com/yoshuawuyts/fd-lock/issues/34. Let me know if I should also add a function like `fn unlock(self) -> Result<Self, (self, std::io::Error)>` to the locks.
> Ignore errors while dropping a lock

- Cargo.toml
Tempfile, is-terminal, and others are updating to 0.37 now, so update fd-lock too.
> Update to rustix 0.37.

- .github/workflows/ci.yaml
It's good to use a versioned dependency anyway, and this may also fix the failure at:
https://github.com/yoshuawuyts/fd-lock/actions/runs/5249297721
> Switch from actions/checkout@master to actions/checkout@v3

- Cargo.toml
This speeds up clean builds by about 50%.
> Update to rustix 0.38.

- src/read_guard.rs
- src/rw_lock.rs
- src/sys/mod.rs
- src/sys/unix/read_guard.rs
- src/sys/unix/rw_lock.rs
- src/sys/unix/write_guard.rs
- src/sys/windows/read_guard.rs
- src/sys/windows/rw_lock.rs
- src/sys/windows/write_guard.rs
- src/write_guard.rs
This implements the idea in https://github.com/yoshuawuyts/fd-lock/issues/12.
Switch public APIs from `AsRawFd`/`AsRawHandle` to the new I/O safety
traits `AsFd`/`AsHandle`. On Unix platforms, use `rustix` to avoid
manipulating raw file descriptors altogether.
This uses `AsFd` and `AsHandle` from the `io-lifetimes` crate, which are
identical to traits which will hopefully be landing in libstd soon.
> Use the new I/O safety traits, using rustix

- Cargo.toml
No changes are needed, and Rust 2021 Edition is supported in Rust 1.56.0 so this doesn't affect the effective MSRV.
> Update to Rust 2021 Edition.

- src/sys/unix/mod.rs
- src/sys/unix/read_guard.rs
- src/sys/unix/rw_lock.rs
- src/sys/unix/write_guard.rs
Haven't tested it yet; I will write here once I confirm it works on Solaris.
(bumped the package version too as we need a new release, please let me know if I should revert that commit)
> Target support: solaris

- .github/workflows/ci.yaml
- Cargo.toml
`fd-lock` is the last crate in my lockfile that uses windows-sys v0.52.0. Relax the version constraint on `windows-sys` and add tests in CI for both versions.
I also tested this locally on a Windows box.
I would love to see this change released on Crates.io. If you'd like, I can prep `Cargo.toml` for that as well in a v4.1.0 release.
Thanks!
> Support windows-sys v0.59.0

- README.md
Hi! I fixed a broken link to the contributing guidelines in the project's `README.md`. The previous link had an incorrect path structure.
> fix: update dead link
